### ISSUE TITLE
Installation error, plugin "requires WordPress Popular Posts in order to work"

### ISSUE THREAD

**Issue by kienitzpaia** [cabrerahector/wordpress-popular-posts-feed#3]
Wp popular post feed can't be recognised, however the the dependence WordPress Popular Posts have been installed and run well.
<img width="1515" alt="Screenshot 2023-08-07 at 21 57 43" src="https://github.com/cabrerahector/wordpress-popular-posts-feed/assets/33316084/9b209fef-54a2-46b3-9c5a-91330978db08">

**Comment by cabrerahector** [comment]
Hi @kienitzpaia (I think you contacted me via email as well?),

You're running an outdated version of the Popular Posts Feed plugin, that's why you're getting that error message. Please grab the latest version from the [Releases](https://github.com/cabrerahector/wordpress-popular-posts-feed/releases) pages and install it on your site.

**Comment by kienitzpaia** [comment]
Thank you for the investigation, it solved the problem!
